<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Storage\" />
    <Folder Include="Native\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirPad.Core\AirPad.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
  </ItemGroup>

</Project>
